import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  WHATSAPP_MESSAGE_ACK_STATUS_DEVICE_OPTION_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_ERROR_OPTION_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_FIELD_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_PENDING_OPTION_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_PLAYED_OPTION_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_READ_OPTION_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_SERVER_OPTION_ID,
  WHATSAPP_MESSAGE_ACK_STATUS_UNKNOWN_OPTION_ID,
  WHATSAPP_MESSAGE_DIRECTION_FIELD_ID,
  WHATSAPP_MESSAGE_DIRECTION_INBOUND_OPTION_ID,
  WHATSAPP_MESSAGE_DIRECTION_OUTBOUND_OPTION_ID,
  WHATSAPP_MESSAGE_EXTERNAL_ID_FIELD_ID,
  WHATSAPP_MESSAGE_HAS_MEDIA_FIELD_ID,
  WHATSAPP_MESSAGE_MEDIA_MIME_TYPE_FIELD_ID,
  WHATSAPP_MESSAGE_OBJECT_ID,
  WHATSAPP_MESSAGE_RAW_PAYLOAD_FIELD_ID,
  WHATSAPP_MESSAGE_REPLY_TO_EXTERNAL_ID_FIELD_ID,
  WHATSAPP_MESSAGE_SENDER_ID_FIELD_ID,
  WHATSAPP_MESSAGE_SENDER_NAME_FIELD_ID,
  WHATSAPP_MESSAGE_SENT_AT_FIELD_ID,
  WHATSAPP_MESSAGE_TEXT_FIELD_ID,
  WHATSAPP_MESSAGE_WA_MESSAGE_ID_FIELD_ID,
} from '../constants/universal-identifiers';

export enum WhatsappMessageDirection {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
}

// Mirrors the WAHA/WhatsApp ack ladder.
export enum WhatsappMessageAckStatus {
  UNKNOWN = 'UNKNOWN',
  ERROR = 'ERROR',
  PENDING = 'PENDING',
  SERVER = 'SERVER',
  DEVICE = 'DEVICE',
  READ = 'READ',
  PLAYED = 'PLAYED',
}

export default defineObject({
  universalIdentifier: WHATSAPP_MESSAGE_OBJECT_ID,
  nameSingular: 'whatsappMessage',
  namePlural: 'whatsappMessages',
  labelSingular: 'WhatsApp Message',
  labelPlural: 'WhatsApp Messages',
  description: 'A single WhatsApp message imported from WAHA',
  icon: 'IconMessage',
  // The message body, not externalId: Twenty forces the label identifier to be
  // the first visible column, and a composite WAHA id makes a useless one.
  labelIdentifierFieldMetadataUniversalIdentifier: WHATSAPP_MESSAGE_TEXT_FIELD_ID,
  fields: [
    {
      universalIdentifier: WHATSAPP_MESSAGE_EXTERNAL_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'externalId',
      label: 'External ID',
      description:
        'Full composite WAHA message id; the idempotency key for ingestion',
      icon: 'IconKey',
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_WA_MESSAGE_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'waMessageId',
      label: 'WhatsApp message ID',
      description: 'Raw WhatsApp message id, without the composite prefix',
      icon: 'IconHash',
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_TEXT_FIELD_ID,
      type: FieldType.TEXT,
      name: 'text',
      label: 'Text',
      icon: 'IconMessage',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_SENT_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'sentAt',
      label: 'Sent at',
      icon: 'IconClock',
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_DIRECTION_FIELD_ID,
      type: FieldType.SELECT,
      name: 'direction',
      label: 'Direction',
      icon: 'IconArrowsExchange',
      defaultValue: `'${WhatsappMessageDirection.INBOUND}'`,
      options: [
        {
          id: WHATSAPP_MESSAGE_DIRECTION_INBOUND_OPTION_ID,
          value: WhatsappMessageDirection.INBOUND,
          label: 'Inbound',
          position: 0,
          color: 'green',
        },
        {
          id: WHATSAPP_MESSAGE_DIRECTION_OUTBOUND_OPTION_ID,
          value: WhatsappMessageDirection.OUTBOUND,
          label: 'Outbound',
          position: 1,
          color: 'blue',
        },
      ],
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_ACK_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'ackStatus',
      label: 'Ack status',
      description: 'Delivery acknowledgement reported by WhatsApp',
      icon: 'IconChecks',
      isNullable: true,
      options: [
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_UNKNOWN_OPTION_ID,
          value: WhatsappMessageAckStatus.UNKNOWN,
          label: 'Unknown',
          position: 0,
          color: 'gray',
        },
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_ERROR_OPTION_ID,
          value: WhatsappMessageAckStatus.ERROR,
          label: 'Error',
          position: 1,
          color: 'red',
        },
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_PENDING_OPTION_ID,
          value: WhatsappMessageAckStatus.PENDING,
          label: 'Pending',
          position: 2,
          color: 'orange',
        },
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_SERVER_OPTION_ID,
          value: WhatsappMessageAckStatus.SERVER,
          label: 'Server',
          position: 3,
          color: 'yellow',
        },
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_DEVICE_OPTION_ID,
          value: WhatsappMessageAckStatus.DEVICE,
          label: 'Device',
          position: 4,
          color: 'blue',
        },
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_READ_OPTION_ID,
          value: WhatsappMessageAckStatus.READ,
          label: 'Read',
          position: 5,
          color: 'green',
        },
        {
          id: WHATSAPP_MESSAGE_ACK_STATUS_PLAYED_OPTION_ID,
          value: WhatsappMessageAckStatus.PLAYED,
          label: 'Played',
          position: 6,
          color: 'purple',
        },
      ],
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_SENDER_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'senderId',
      label: 'Sender ID',
      description: 'Sender jid or lid',
      icon: 'IconUser',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_SENDER_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'senderName',
      label: 'Sender name',
      icon: 'IconUserCircle',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_REPLY_TO_EXTERNAL_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'replyToExternalId',
      label: 'Reply to',
      description: 'External id of the message this one quotes',
      icon: 'IconArrowBackUp',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_HAS_MEDIA_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'hasMedia',
      label: 'Has media',
      icon: 'IconPaperclip',
      defaultValue: false,
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_MEDIA_MIME_TYPE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'mediaMimeType',
      label: 'Media MIME type',
      icon: 'IconFileTypography',
      isNullable: true,
    },
    {
      universalIdentifier: WHATSAPP_MESSAGE_RAW_PAYLOAD_FIELD_ID,
      type: FieldType.RAW_JSON,
      name: 'rawPayload',
      label: 'Raw payload',
      description:
        'Channel-specific extras kept verbatim so new WhatsApp features need no schema change',
      icon: 'IconCode',
      isNullable: true,
    },
  ],
});
